version: "3"
services:

  analise-credito-cqrs-db:
    image: postgres:latest
    container_name: "analisecreditodb"
    environment:
      POSTGRES_DB: "analisecreditodb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      TZ: "GMT"
    volumes:
      - '/home/ruibraz/dev/postgres/analisecreditodb:/var/lib/postgresql/data'
    ports:
      - "5433:5432"
    networks:
      - postgres-analisecreditodb

  pgadmin4:
    image: dpage/pgadmin4:4.10
    container_name: "analisecreditopgadmin4"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin"
      PGADMIN_DEFAULT_PASSWORD: "secret"
    ports:
      - "8082:80"
    networks:
      - pgadmin

networks:
  postgres-analisecreditodb:
  pgadmin:
