#Database Config

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/analisecreditodb
    username: postgres
    password: postgres
    databaseName: analisecreditodb
  jpa:
    database-platform: postgres
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect


